language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm run test
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm start;
    bash travis_deploy.sh;
  else
    npm run build;
  fi
after_success:
- npm run codecov
env:
  global:
  - GH_REF: komitywa/plantingjs.git
